# Build project and run unit tests

name: build-test
on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
